"""Conjugator rules, checked against the sheet's full tables and known forms."""
import csv
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from conjugate import conjugate  # noqa: E402

TENSES = {"Present": "present", "Perfet": "perfet", "Imperfet": "imperfet",
          "Passat perifràstic": "perifrastic", "Futur": "futur", "Condicional": "condicional",
          "Present de subjuntiu": "subjuntiu"}
SHEET_ERRORS = {"trucar", "plegar"}
NOT_REGULAR = {"sentir"}   # "Regular" in the sheet but not an -eix- verb


def ap(x):
    return x.replace("'", "’")


class SheetTables(unittest.TestCase):
    def test_regular_verbs_match_the_sheet(self):
        with open(ROOT / "data/source/verbs_by_unit.csv", encoding="utf-8") as f:
            rows = list(csv.reader(f))
        h = rows[0]
        checked = 0
        for x in rows[1:]:
            verb = x[h.index("Verb")]
            if x[h.index("Verb Category")] != "Regular" or "jo:" not in x[h.index("Present")]:
                continue
            if verb in SHEET_ERRORS or verb in NOT_REGULAR:
                continue
            res = conjugate(verb)
            if res is None:     # -er/-re verbs: not generated by rule
                continue
            conj, part, ger = res
            for col, key in TENSES.items():
                want = [ap(l.split(":", 1)[1].strip()) for l in x[h.index(col)].split("\n") if l.strip()]
                self.assertEqual(conj[key], want, f"{verb} {key}")
            want_imp = [ap(l.strip()) for l in x[h.index("Imperatiu")].split("\n") if l.strip()]
            self.assertEqual(conj["imperatiu"], want_imp, f"{verb} imperatiu")
            self.assertEqual(part, x[h.index("Participi")], verb)
            self.assertEqual(ger, x[h.index("Gerundi")], verb)
            checked += 1
        self.assertGreaterEqual(checked, 17)


class Rules(unittest.TestCase):
    def check(self, verb, tense, forms):
        self.assertEqual(conjugate(verb)[0][tense], forms.split(", "), f"{verb} {tense}")

    def test_spelling_changes(self):
        self.check("tocar", "present", "toco, toques, toca, toquem, toqueu, toquen")
        self.check("pagar", "subjuntiu", "pagui, paguis, pagui, paguem, pagueu, paguin")
        self.check("començar", "present", "començo, comences, comença, comencem, comenceu, comencen")
        self.check("menjar", "present", "menjo, menges, menja, mengem, mengeu, mengen")
        self.check("trucar", "present", "truco, truques, truca, truquem, truqueu, truquen")
        self.check("plegar", "imperatiu", "plega, plegui, pleguem, plegueu, pleguin")

    def test_diaeresis(self):
        self.check("estudiar", "subjuntiu", "estudiï, estudiïs, estudiï, estudiem, estudieu, estudiïn")
        self.check("continuar", "imperatiu", "continua, continuï, continuem, continueu, continuïn")
        self.check("crear", "subjuntiu", "creï, creïs, creï, creem, creeu, creïn")
        self.check("construir", "imperfet", "construïa, construïes, construïa, construíem, construíeu, construïen")
        self.check("construir", "present", "construeixo, construeixes, construeix, construïm, construïu, construeixen")
        self.check("explicar", "subjuntiu", "expliqui, expliquis, expliqui, expliquem, expliqueu, expliquin")
        c, part, ger = conjugate("produir")
        self.assertEqual((part, ger), ("produït", "produint"))

    def test_inchoative_ir(self):
        self.check("servir", "present", "serveixo, serveixes, serveix, servim, serviu, serveixen")
        self.check("servir", "imperatiu", "serveix, serveixi, servim, serviu, serveixin")
        self.check("llegir", "futur", "llegiré, llegiràs, llegirà, llegirem, llegireu, llegiran")

    def test_pronominal(self):
        self.check("aixecar-se", "present", "m’aixeco, t’aixeques, s’aixeca, ens aixequem, us aixequeu, s’aixequen")
        self.check("aixecar-se", "perfet", "m’he aixecat, t’has aixecat, s’ha aixecat, ens hem aixecat, us heu aixecat, s’han aixecat")
        self.check("aixecar-se", "perifrastic", "em vaig aixecar, et vas aixecar, es va aixecar, ens vam aixecar, us vau aixecar, es van aixecar")
        self.check("aixecar-se", "imperatiu", "aixeca’t, aixequi’s, aixequem-nos, aixequeu-vos, aixequin-se")
        self.check("dutxar-se", "present", "em dutxo, et dutxes, es dutxa, ens dutxem, us dutxeu, es dutxen")
        self.check("divertir-se", "imperatiu", "diverteix-te, diverteixi’s, divertim-nos, divertiu-vos, diverteixin-se")
        self.assertEqual(conjugate("aixecar-se")[2], "aixecant-se")

    def test_shared_forms(self):
        c, part, ger = conjugate("parlar")
        self.assertEqual(c["imperfet"], "parlava, parlaves, parlava, parlàvem, parlàveu, parlaven".split(", "))
        self.assertEqual(c["condicional"], "parlaria, parlaries, parlaria, parlaríem, parlaríeu, parlarien".split(", "))
        self.assertEqual(c["perifrastic"][0], "vaig parlar")
        self.assertEqual((part, ger), ("parlat", "parlant"))

    def test_not_conjugated(self):
        self.assertIsNone(conjugate("perdre"))
        self.assertIsNone(conjugate("anar-se'n"))


if __name__ == "__main__":
    unittest.main()
